version: "3"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.11.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: prod_db
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
