version: "3"

services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_RUN_HOST=0.0.0.0
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=taskfracture
    volumes:
      - ./app:/usr/src/app/app
      - ./requirements.txt:/usr/src/app/requirements.txt
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskfracture
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
