version: "3"

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=prod_db
      - DB_USERNAME=admin
      - DB_PASSWORD=LfD7dWMjGD9x
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.11.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: LfD7dWMjGD9x
      MYSQL_DATABASE: prod_db
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
